---
config:
  layout: dagre
---
flowchart TB
%% Nodes
    sed0("Software Engineering Director: Receive instructions to generate a change plan")
    sed1{"Software Engineering Director: Determine if more information is needed to create or update the overview section of the change plan"}
    sed2["Software Engineering Director: Ask User Assistant for desired information"]
    sed3["Software Engineering Director: Create or update overview section of change plan"]
    sed4["Software Engineering Director: Instruct Specifier to enrich plan with detailed specification changes"]
    sed5{"Software Engineering Director: Review specification changes and determine if they're aligned with (i) the plan overview and (ii) the instructions and information provided by the User Assistant"}
    sed6["Software Engineering Director: Inform Specifier of misalignment details and instruct Specifier to revise specification changes to be aligned"]
    sed7["Software Engineering Director: Instruct Software Architect to enrich plan with a detailed implementation architecture section"]
    sed8{"Software Engineering Director: Review implementation architecture and determine if it's aligned with (i) the plan overview, (ii) the specification changes, and (iii) the instructions and information provided by the User Assistant"}
    sed9["Software Engineering Director: Inform Software Architect of misalignment details and instruct Software Architect to revise implementation architecture section to be aligned"]
    sed10["Software Engineering Director: Inform User Assistant that the change plan is authored"]

    ua0["User Assistant: Ask user for desired information"]
    ua1["User Assistant: Provide user-supplied information to Software Engineering Director"]
    ua2("User Assistant: Notify the user that the change plan is authored")

    u["User: Provide information to User Assistant"]

    s0{"Specifier: Determine if additional information is needed to create or update the change plan's detailed specification changes"}
    s1["Specifier: Ask Software Engineering Director for additional information"]
    s2["Specifier: Enrich change plan with detailed specification changes aligned with (i) the plan overview and (ii) the instructions and information provided by the Software Engineering Director"]
    s3["Specifier: Notify Software Engineering Director that the specification changes are ready for review"]   

    sa0{"Software Architect: Determine if additional information is needed to create or update the change plan's detailed implementation architecture"}
    sa1["Software Architect: Ask Software Engineering Director for additional information"]
    sa2["Software Architect: Enrich change plan with detailed implementation architecture aligned with (i) the plan overview, (ii) the specification changes, and (iii) the instructions and information provided by the Software Engineering Director"]
    sa3["Software Architect: Notify Software Engineering Director that the implementation architecture section is ready for review"]

%% Edges
    
    %% Overview Section Authoring
    sed0 --> sed1
    sed1 -- "More information desired" --> sed2
    sed1 -- "No more information desired" --> sed3
    sed2 --> ua0
    ua0 --> u
    u --> ua1  
    ua1 --> sed1
    sed3 --> sed4

    %% Specification Changes Authoring
    sed4 --> s0
    s0 -- "More information desired" --> s1
    s1 --> sed2
    s0 -- "No information desired" --> s2
    s2 --> s3
    s3 --> sed5
    sed5 -- "Specification changes are not aligned with the (i) plan overview, (ii) information supplied by the User Assistant, or (iii) instructions supplied by the User Assistant" --> sed6
    sed6 --> s0
    sed5 -- "Specification changes are aligned with the (i) plan overview, (ii) information supplied by the User Assistant, and (iii) instructions supplied by the User Assistant" --> sed7

    %% Software Architecture Changes Authoring
    sed7 --> sa0
    sa0 -- "More information desired" --> sa1
    sa1 --> sed2
    sa0 -- "No information desired" --> sa2
    sa2 --> sa3
    sa3 --> sed8
    sed8 -- "Implementation architecture is not aligned with the (i) plan overview, (ii) plan specifications, (iii) information supplied by the User Assistant, or (iv) instructions supplied by the User Assistant" --> sed9
    sed9 --> sa0
    sed8 -- "Implementation architecture is aligned with the (i) plan overview, (ii) plan specifications, (iii) information supplied by the User Assistant, and (iv) instructions supplied by the User Assistant" --> sed10
    sed10 --> ua2